int autoVarReturn();
void deploy();
void runAutoTester();
void runAutoTesterBlue();
void runAutoPID();
void runAutoenc();
void runAuto10Test();
void runAuto10Small();
void runAuto(int autoNumber);
int autoSelector();
int autoIndicator();