#pragma config(Motor,  port1,           lift,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frwheel,       tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           flwheel,       tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           brwheel,       tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           blwheel,       tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//int speed =
float speed = 82.7959;

task main()
{
if (speed == 82.7959){
	motor (lift) = 127;
}
else {
	motor (lift) = 0;
}


}
