double getDriveFL();
double getDriveFR();
double getDriveBL();
double getDriveBR();
double getDriveR();
double getDriveL();
double getDriveF();
double getDriveB();
double getDrive();
void driveReset();
double getHeatFL();
double getHeatFR();
double getHeatBL();
double getHeatBR();
void setDrive(double lSpeed, double rSpeed);
void setDriveFull(double flSpeed, double blSpeed, double frSpeed, double brSpeed);
void setFL(double speed);
void setFR(double speed);
void setBL(double speed);
void setBR(double speed);
void driveBrake();
void driveCoast();
void driveTime(int dir, double speed, double timeVal);
void setDriveTime(double speedL, double speedR, double timeVal);
int goP(int dir, double initSpeed, double speed, double dist, double speedStart, double speedCut, double slowFactor, bool smooth);
int turnP(int dir, double initSpeed, double speed, double dist, double speedStart, double speedCut, double slowFactor, bool smooth);